# Generated by Django 6.0 on 2026-01-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_tier_remove_price_product_price_tier_delete_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="tier",
            name="manifest",
            field=models.JSONField(
                default=list,
                help_text="A list of notification channel strings defining the schedule for this tier.",
            ),
        ),
    ]
