# Generated by Django 6.0 on 2025-12-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencycontact",
            name="relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
