# Generated by Django 6.0 on 2025-12-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_password_reset_last_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="hash_backup_phone",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="hash_secondary_backup_email",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="secondary_backup_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
