# Generated by Django 6.0 on 2025-12-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_agreed_to_terms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="backup_phone",
        ),
    ]
