# Generated by Django 6.0 on 2025-12-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_backup_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(default=45, max_length=5),
            preserve_default=False,
        ),
    ]
