# Generated by Django 5.2.9 on 2025-12-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="weeks_in_advance",
            field=models.PositiveIntegerField(
                default=4,
                help_text="The number of weeks in advance to start sending notifications.",
            ),
        ),
    ]
