# Generated by Django 5.2.9 on 2025-12-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_weeks_in_advance"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes to provide more context about the event.",
                null=True,
            ),
        ),
    ]
