# Generated by Django 6.0 on 2025-12-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="notification_start_date",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="The auto-calculated date when notifications will begin.",
                null=True,
            ),
        ),
    ]
