# Generated by Django 6.0 on 2025-12-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="The email address to block.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the email was added to the blocklist.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked Email",
                "verbose_name_plural": "Blocked Emails",
                "ordering": ["-created_at"],
            },
        ),
    ]
