# Generated by Django 6.0 on 2025-12-14 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version number, e.g., '1.0'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The full HTML content of the terms and conditions."
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time this version was published.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Terms and Conditions",
                "ordering": ["-published_at"],
            },
        ),
    ]
