# Generated by Django 6.0 on 2025-12-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="recipient_contact_info",
            field=models.CharField(
                blank=True,
                help_text="The contact info used for sending. Populated after the notification is sent.",
                max_length=255,
                null=True,
            ),
        ),
    ]
